### ISSUE TITLE
CORS error for localhost:5173

### ISSUE THREAD

**Issue by mrwhite-hu** [RobertWatkin/laravel-vue-saas-boilerplate#1]
When I try to open localhost I get CORS error localhost:5173 messages for loading the app.

**Comment by robert-watkin** [comment]
Could you please provide more details on how you encountered this error. Steps you carried out prior to this issue occurring. I have followed the steps again listed in the README.md file on a new system and it has been successful. I have not encountered the CORS issue

For more information on CORS issues this page may help:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
